server:
  port: 80

spring:
  application:
    name: cloud-order-service
  # Consul
  cloud:
    consul:
      host: docker.jpldx.com
      port: 8500
      discovery:
        service-name: ${spring.application.name}
