server:
  port: 80

spring:
  application:
    name: cloud-order-service


eureka:
  client:
    register-with-eureka: true # 是否将自己注册进EurekaServer
    fetch-registry: true # 是否从EurekaServer抓取已有的注册信息，单节点无所谓，集群必须设置为true才能配合Ribbon实现负载均衡
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # 集群配置
      defaultZone: http://eureka7001.com:7001/eureka/
