server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com # Eureka 服务端实例名称

  client:
    register-with-eureka: false # 不向注册中心注册自己
    fetch-registry: false # 职责是维护服务实例，并不需要去检索服务
    # 设置与 Eureka Server 交互的服务注册和服务查询地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/