server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com # Eureka 服务端实例名称

  client:
    register-with-eureka: false # 不向注册中心注册自己
    fetch-registry: false # 职责是维护服务实例，并不需要去检索服务
    # 设置与 Eureka Server 交互的服务注册和服务查询地址
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/ # eureka 集群配置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    enable-self-preservation: false        # 关闭自我保护机制，保证不可用服务被及时剔除
    eviction-interval-timer-in-ms: 10000    # 心跳检测时间